services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      target: dev
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=trigger log_level=0"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/hosts:/etc/nginx/conf.d
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db-data:
  redis-data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
