services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      target: dev
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=trigger log_level=0"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  products_mysql:
    image: mysql:8.0
    volumes:
      - products-data:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"

  reviews_mysql:
    image: mysql:8.0
    volumes:
      - reviews-data:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3307:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/hosts:/etc/nginx/conf.d
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  products-data:
  reviews-data:
  redis-data:
