# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/*'
#            - '../src/Kernel.php'

    App\Infrastructure\Http\:
        resource: '../src/Infrastructure/Http'
        tags: ['controller.service_arguments']

    App\Domain\Product\Repository\ProductRepositoryInterface:
        class: App\Infrastructure\Doctrine\Repository\DoctrineProductRepository
        arguments:
            - '@doctrine.orm.default_entity_manager'

    App\Domain\Product\Factory\ProductFactoryInterface: '@App\Infrastructure\Factory\ProductFactory'

    ### Buses
    App\Application\Product\Command\CreateProduct\CreateProductCommandHandler:
        tags: ['messenger.message_handler']

    App\Application\Product\Command\UpdateProduct\UpdateProductCommandHandler:
        tags: ['messenger.message_handler']

    App\Application\Product\Command\DeleteProduct\DeleteProductCommandHandler:
        tags: ['messenger.message_handler']

    App\Application\Product\Query\GetProductById\GetProductByIdQueryHandler:
        tags: ['messenger.message_handler']

    App\Application\Product\Query\ListProducts\ListProductsQueryHandler:
        tags: ['messenger.message_handler']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
